# Mercury configuration file

# absolute path or relative to "Mercury.jl" parent directory
db_dir = "../data/"
storage_dir = "../data/"
logfile = "../data/mercury.log"

skip_malware_check = false

# disable access log for better performance
disable_access_log = false

[network]
ip = "127.0.0.1"
port = 8000

# access from IPs outside below subnets will be considered external
internal_subnets = ["127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

# allow access from external (external = not from internal_subnets) client IPs
allow_external_access = true

# base URL of the mercury instance in the internal resp. external network
internal_url = "https://localhost"
external_url = "https://fileexchange.ddns.net"

[retention]
# retention times in hours
min = 0
default = 48
max = inf

# after retention time a data set is soft deleted, purge time (in hours) after the soft delete, the data set gets hard deleted
purge = 48

# clean up interval in seconds
interval = 300

[limits]
# in bytes
# put "inf" for infinite
filesize = 8388608000
filenumber_per_dataset = 1000000
datasetsize = 8388608000
datasetnumber = 1000000
storage = 21000000000