# Mercury configuration file

# absolute path or relative to "Mercury.jl" parent directory
db_dir = "../data/"
storage_dir = "../data/"
skip_malware_check = false

[network]
ip = "0.0.0.0"
port = 8000

[retention]
# retention times in hours
min = 0
default = 48
max = inf

# after retention time a data set is soft deleted, purge time (in hours) after the soft delete, the data set gets hard deleted
purge = 48

# clean up interval in seconds
interval = 300

[limits]
# in bytes
# put "inf" for infinite
filesize = 838860800
filenumber_per_dataset = 1000000
datasetsize = 838860800
datasetnumber = 1000000
storage = 20000000000