# Mercury configuration file

# absolute path or relative to "Mercury.jl" parent directory
db_dir = "../data/"
storage_dir = "../data/"

debug = true

[network]
ip = "0.0.0.0"
port = 8000

[retention] # retention times in hours
min = 0
default = 48
max = inf

[limits] # in bytes
filesize = inf
storagesize = inf